### ISSUE TITLE
Signal detection buffer Index out of bounds lager than 1

### ISSUE THREAD

**Issue by skewyapp** [skewyapp/skewy1-0#11]
**Describe the bug**
* Index of signalDetectionFromBuffer out of bounds
* App will crash

**To Reproduce**
* Unable to reproduce
* Probably happens when user tries to change signal length

**Expected behavior**
* No crash, array size is limited through input filters

**Screenshots**
* n/a

**Smartphone (please complete the following information):**
 - All devices
 - App release 7.0

**Additional context**
Exception java.lang.IndexOutOfBoundsException: Index: 85, Size: 85
  at java.util.ArrayList.get (ArrayList.java:437)
  at com.example.skewy.audioprocessing.SignalDetection.signalDetectionFromBuffer (SignalDetection.kt:113)
  at com.example.skewy.service.RecorderService$startRecording$1.invokeSuspend (RecorderService.kt:237)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:570)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:749)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:677)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:664)

**Comment by skewyapp** [comment]
Still happens in 8.0

Exception java.lang.IndexOutOfBoundsException: Index: 9, Size: 9
  at java.util.ArrayList.get (ArrayList.java:437)
  at hans.b.skewy1_0.audioprocessing.SignalDetection.signalDetectionFromBuffer (SignalDetection.kt:110)
  at hans.b.skewy1_0.service.RecorderService$startRecording$1.invokeSuspend (RecorderService.kt:238)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:570)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:749)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:677)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:664)

**Comment by skewyapp** [comment]
It occurs while  signal is detected and the signal length is being changed

E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-8
    Process: hans.b.skewy1_0, PID: 10390
    java.lang.IndexOutOfBoundsException: Index: 14, Size: 14
        at java.util.ArrayList.get(ArrayList.java:437)
        at hans.b.skewy1_0.audioprocessing.SignalDetection.signalDetectionFromBuffer(SignalDetection.kt:110)
        at hans.b.skewy1_0.service.RecorderService$startRecording$1.invokeSuspend(RecorderService.kt:238)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@87f2224, Dispatchers.Default]
